import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>No Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">No Code DL!</a>
        </h1>

        {/* <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p> */}

        <div className={styles.grid}>
          <Link href="/image-processing/projects/projects" className={styles.card}>
            <h2>Image Processing &rarr;</h2>
            <p>Create image Processing models and perform image related tasks.</p>
          </Link>

          <Link href="/text-prototyping/projects/projects" className={styles.card}>
            <h2>Text / Sequence Prototyping &rarr;</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptatibus.</p>
          </Link>

          <Link
            href="/standard-networks/projects/projects"
            className={styles.card}
          >
            <h2>Standard Networks &rarr;</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Omnis.</p>
          </Link>


        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
